# Generated by Django 4.1.7 on 2023-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('co_author', models.CharField(max_length=30)),
                ('register_date', models.DateField()),
                ('borrowed', models.BooleanField(default=False)),
                ('borrower_name', models.CharField(max_length=30)),
                ('borrow_date', models.DateTimeField()),
                ('borrow_return', models.DateTimeField()),
                ('borrow_time', models.DateField()),
            ],
        ),
    ]
