# Generated by Django 4.1.7 on 2023-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_return',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='co_author',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
