# Generated by Django 4.1.7 on 2023-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_borrow_date_alter_book_borrow_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
    ]
