# Generated by Django 4.1.7 on 2023-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
