# Generated by Django 4.1.7 on 2023-02-24 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='register_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
