# Generated by Django 4.1.7 on 2023-02-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrow_return',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrow_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrower_name',
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(blank=True, max_length=30)),
                ('borrow_date', models.DateTimeField(blank=True, null=True)),
                ('borrow_return', models.DateTimeField(blank=True, null=True)),
                ('borrow_time', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.book')),
            ],
        ),
    ]
