# Generated by Django 4.1.7 on 2023-02-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_active'),
        ('book', '0008_remove_book_borrow_date_remove_book_borrow_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrower_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
    ]
