# Generated by Django 4.1.7 on 2023-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_borrow_borrower_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
